apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo  # Должно совпадать с меткой в вашем Deployment
  ports:
    - protocol: TCP
      port: 27017        # Внутренний порт кластера
      targetPort: 27017  # Порт внутри контейнера
      nodePort: 32586     # Внешний порт для доступа
  type: NodePort          # NodePort для доступа снаружи кластера
