apiVersion: v1
kind: Service
metadata:
  name: filestorage-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: filestorage
  ports:
    - port: 80
      targetPort: 50205
      protocol: TCP
      nodePort: 32585